version: "3"
services:
  db:
    image: postgres:14
    container_name: pgdb
    environment:
      POSTGRES_USER: shivansh_sinha
      POSTGRES_PASSWORD: codhodtod
      POSTGRES_DB: goapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
