version: "3"
services:
  db:
    image: postgres:14
    container_name: pgdb
    environment:
      POSTGRES_USER: 	postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goapi
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
